# Generated by Django 6.1 on 2026-08-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_alter_person_options_alter_pipeline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='share_owner_contact',
            field=models.BooleanField(default=False, verbose_name='Compartilhar Contato do Proprietário com Outros Corretores'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Disponível'), ('draft', 'Rascunho / Cadastro Rápido'), ('under_negotiation', 'Em Negociação'), ('reserved', 'Reservado'), ('sold', 'Vendido'), ('rented', 'Alugado'), ('inactive', 'Inativo / Arquivado')], default='available', max_length=20, verbose_name='Status'),
        ),
    ]
