# Generated by Django 6.1 on 2026-08-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_property_share_owner_contact_alter_property_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyvisit',
            old_name='property',
            new_name='visit_property',
        ),
        migrations.AddField(
            model_name='activity',
            name='task_type',
            field=models.CharField(choices=[('call', '📞 Ligar para Cliente'), ('visit_followup', '🏠 Follow-up de Visita'), ('document', '📄 Documentação / Certidões'), ('credit_analysis', '🏦 Análise de Crédito'), ('proposal', '📝 Elaborar Proposta'), ('general', '📋 Tarefa Geral')], default='general', max_length=20, verbose_name='Categoria da Tarefa'),
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='action_type',
            field=models.CharField(choices=[('note', 'Anotação Interna'), ('stage_change', 'Mudança de Estágio no Funil'), ('whatsapp_sent', 'WhatsApp Registrado'), ('call_logged', 'Ligação Registrada'), ('visit_scheduled', 'Visita Agendada'), ('visit_completed', 'Visita Realizada'), ('visit_feedback', 'Feedback de Visita'), ('key_action', 'Movimentação de Chave'), ('proposal_sent', 'Proposta Enviada'), ('status_change', 'Status Alterado'), ('task_created', 'Tarefa/Lembrete Criado')], default='note', max_length=30, verbose_name='Tipo de Registro'),
        ),
    ]
