# Generated by Django 6.1 on 2026-08-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fase5_visits_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylead',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento / Perda'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monthly_goal',
            field=models.DecimalField(decimal_places=2, default=500000.0, max_digits=12, verbose_name='Meta Mensal de VGV (R$)'),
        ),
    ]
