# Generated by Django 6.1 on 2026-08-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fase6_dashboard_bi'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título do Modelo')),
                ('category', models.CharField(choices=[('welcome', '👋 Primeiro Contato / Boas-vindas'), ('match', '🏠 Apresentação de Imóvel (Match)'), ('visit', '📅 Confirmação / Agendamento de Visita'), ('credit_doc', '📄 Documentação & Análise de Crédito'), ('proposal', '🤝 Proposta & Negociação'), ('follow_up', '⏰ Reativação / Follow-up'), ('general', '💬 Mensagem Geral')], default='welcome', max_length=30, verbose_name='Categoria')),
                ('content', models.TextField(help_text='Tags disponíveis: {nome_cliente}, {primeiro_nome}, {codigo_imovel}, {titulo_imovel}, {bairro}, {valor}, {nome_corretor}, {telefone_corretor}', verbose_name='Conteúdo da Mensagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo de Mensagem WhatsApp',
                'verbose_name_plural': 'Modelos de Mensagens WhatsApp',
                'ordering': ['category', 'title'],
            },
        ),
    ]
